package com.spring.jhs.persistence;
// Generated 13-jul-2016 18:51:10 by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;

/**
 * Alumnos generated by hbm2java
 */
@Entity
@Table(name = "alumnos")
public class Alumnos implements java.io.Serializable {

    @Id
    private int matricula;
    @ManyToOne()
    @JoinColumn(name = "usuario")
    private Login login;
    private String nombre;
    private String app;
    private String apm;
    private Integer edad;
    private String sexo;
    @Temporal(javax.persistence.TemporalType.DATE)
    private Date fechaRegistro;

    public Alumnos() {
    }

    public Alumnos(int matricula, Login login) {
        this.matricula = matricula;
        this.login = login;
    }

    public Alumnos(int matricula, Login login, String nombre, String app, String apm, Integer edad, String sexo, Date fechaRegistro) {
        this.matricula = matricula;
        this.login = login;
        this.nombre = nombre;
        this.app = app;
        this.apm = apm;
        this.edad = edad;
        this.sexo = sexo;
        this.fechaRegistro = fechaRegistro;
    }

    public int getMatricula() {
        return this.matricula;
    }

    public void setMatricula(int matricula) {
        this.matricula = matricula;
    }

    public Login getLogin() {
        return this.login;
    }

    public void setLogin(Login login) {
        this.login = login;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getApp() {
        return this.app;
    }

    public void setApp(String app) {
        this.app = app;
    }

    public String getApm() {
        return this.apm;
    }

    public void setApm(String apm) {
        this.apm = apm;
    }

    public Integer getEdad() {
        return this.edad;
    }

    public void setEdad(Integer edad) {
        this.edad = edad;
    }

    public String getSexo() {
        return this.sexo;
    }

    public void setSexo(String sexo) {
        this.sexo = sexo;
    }

    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }

    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }

}
