package com.spring.jhs.persistence;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Bancos generated by hbm2java
 */
@Entity
@Table(name = "BANCOS")
public class Bancos implements java.io.Serializable {

    @Id
    @Column(name="IDBANCO")	
    private int idbanco;
    @Column(name="SBANCO")	
    private String sbanco;
    

    public Bancos() {
    }

    public Bancos(int idbanco, String sbanco) {
        this.idbanco = idbanco;
        this.sbanco = sbanco;
    }

    public int getIdbanco() {
        return this.idbanco;
    }

    public void setIdbanco(int idbanco) {
        this.idbanco = idbanco;
    }

    public String getSbanco() {
        return this.sbanco;
    }

    public void setSbanco(String sbanco) {
        this.sbanco = sbanco;
    }

   
}
