package com.spring.jhs.persistence;
// Generated 13-jul-2016 18:51:10 by Hibernate Tools 3.6.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;

/**
 * Login generated by hbm2java
 */
@Entity
@Table(name = "login")
public class Login implements java.io.Serializable {

    @Id
    @GeneratedValue
    private int id;
    private String usuario;
    private String password;
    private String nombre;
    private Integer edad;
    @Temporal(javax.persistence.TemporalType.DATE)
    private Date fecha;
    private String url;
    @OneToMany(mappedBy="login")
    private Set<Alumnos> alumnos = new HashSet<Alumnos>();

    public Login() {
    }

    public Login(String usuario, int id) {
        this.usuario = usuario;
        this.id = id;
    }

    public Login(String usuario, String password, String nombre, Integer edad, Date fecha, String url, int id, Set alumnos) {
        this.usuario = usuario;
        this.password = password;
        this.nombre = nombre;
        this.edad = edad;
        this.fecha = fecha;
        this.url = url;
        this.id = id;
        this.alumnos = alumnos;
    }

    public String getUsuario() {
        return this.usuario;
    }

    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public Integer getEdad() {
        return this.edad;
    }

    public void setEdad(Integer edad) {
        this.edad = edad;
    }

    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    /**
     * @return the alumnos
     */
    public Set<Alumnos> getAlumnos() {
        return alumnos;
    }

    /**
     * @param alumnos the alumnos to set
     */
    public void setAlumnos(Set<Alumnos> alumnos) {
        this.alumnos = alumnos;
    }

   

}
